//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserInfo
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<short> UserType { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public int Sort { get; set; }
        public string Description { get; set; }
        public string DeptName { get; set; }
    }
}
